:toc: macro
toc::[]

==Modern project structure

With trends such as cloud, microservices, lean, and agile, we decided for a more modern project structure that fits better to recent market trends.
When starting new projects with devonfw, and especially in the context of cloud-native development, we strongly recommend this modern approach over the link:guide-structure-classic[classic structure].

== Modules

Due to trends such as microservices, we are building smaller apps compared to moduliths.
For simplicity, we therefore do not split our app into different modules and keep everything top-level and easy.

In addition to `java` and `resources`, we also add `helm` for helm templates and `docker` for docker scripts (e.g. `Dockerfile`) in `src/main`:

[subs=+macros]
----
├──/src
|  ├──/main
|  |  ├──/docker
|  |  ├──/helm
|  |  ├──/java
|  |  └──/resources
|  └──/test
|     ├──/java
|     └──/resources
└──/pom.xml
----

== Deployment

For modern projects, we strongly recommend that your build process generates the final deliverable as an OCI compliant container.
Further, to go fully cloud-native, you should build your app as a native image via https://www.graalvm.org/[GraalVM] AOT compiler.
Therefore, we recommed to use https://quarkus.io/[quarkus] as your main framework.
In case you want to go with spring, you may consider using https://github.com/spring-projects-experimental/spring-native[spring-native].

== Layers

The package structure of your code inside `src/main/java` (and `src/test/java`) of your app is described in our coding conventions in the sections link:coding-conventions#packages[packages].
For the modern project structure, the layers are defined by the following table:

[options="header"]
|=============================================
|*Layer* | *«layer»* | *Description*
|link:guide-service-layer[service]|`service`|The service layer exposing functionality via its remote API. Typical protocol is link:guide-rest[REST]. May also be any other protocol you are using such as https://grpc.io/[gRPC].
|link:guide-domain-layer[domain]|`domain`|The domain with the data-model and DB access. Use sub-package (in `«detail»`) `repository` for link:guide-repository[repository] and `dao` for link:guide-dao[DAOs]. Also we recommend to put link:guide-jpa#entity[entities] in `model` sub-package.
|link:guide-logic-layer[logic]|`logic`|The logic layer with the functionallity providing the business value.
|link:guide-common[common]|`common`|cross-cutting code not assigned to a technical layer.
|=============================================

== Architecture Mapping

In order to help you to map the architecture, packaging, layering, etc. to the code and see where different code elements should be placed,
we provide this architecture mapping:

[subs=+macros]
----
«root»
├──.link:guide-component#business-component[«component»]
|  ├──.link:guide-domain-layer[domain]
|  |  ├──.link:guide-repository[repo]
|  |  |  ├──.link:guide-repository#repository[«BusinessObject»Repository]
|  |  |  ├──.link:guide-repository#fragment[«BusinessObject»Fragment]
|  |  |  └──.link:guide-repository#fragment[«BusinessObject»FragmentImpl]
|  |  ├──.link:guide-dao[dao] [alternative to repo]
|  |  |  ├──.link:guide-dao#data-access-object[«BusinessObject»Dao]
|  |  |  └──.link:guide-dao#data-access-object[«BusinessObject»DaoImpl]
|  |  └──.model
|  |     └──.link:guide-jpa#entity[«BusinessObject»Entity]
|  ├──.link:guide-logic-layer[logic]
|  |  ├──«BusinessObject»Validator
|  |  └──«BusinessObject»EventsEmitter
|   |  └──.link:guide-usecase[Uc«Operation»«BusinessObject»[Impl]]
|  └──.link:guide-service-layer[rest]
|     └──.link:guide-service-versioning#jax-rs[v1]
|        ├──.link:guide-rest#jax-rs[«Component»RestService]
|        ├──.mapper
|        |     └──.«BusinessObject»Mapper
|        └──.model
|           └──.«BusinessObject»Dto
└──.link:guide-component#general-component[general]
   └──.domain
      └──.model
         └──.ApplicationPersistenceEntity
----
