:toc: macro
toc::[]

==Sample My-Thai-Star application

The My-Thai-Star application is an example implementation for an devon4j web application. It acts as a demo and also shows various integration aspects.

The application showcases the following aspects of the architecture:

- Server configuration
- Transaction management
- Logging usage
- Naming conventions
- Code organization
- Validation
- Database access
- Logic layer implementation patterns



== Logic Layer

The restaurant application showcases two approaches for the logic layer organization. For simple cases the common interface/implementation pattern is used but for more complex logic situations this pattern lacks clarity and can be improved by using the UseCase pattern.

This UseCase pattern divides the Business Facade into several fine grained sub-interfaces and implementations for better maintainability and testability. This pattern has been proven successful in several large scale projects with a big team of developers involved.

Bear in mind that on a real engagement it should be better to opt for one single pattern to code all the appliction
